version: '3'

services:

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app:delegated
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/app:delegated
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - db_data:/var/lib/mysql:delegated
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=cotonti
      - MYSQL_USER=cotonti
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8082:80"
    depends_on:
      - mysql

volumes:
  db_data:

networks:
  cotonti:
